name: "TECHOCTAVE"
description: "We believe software should be beautiful & inspired."

author: "TechOctave, LLC"

url: "https://techoctave.com"
baseurl: ""

#markdown: rdiscount
markdown: kramdown
permalink: /c7/:year/:month/:title.html
#highlighter: pygments
highlighter: rouge

# Google Analytics
ga_domain: techoctave.com
ga_tracking_id: UA-17961498-1
